behaviors:
  DroneAgent:
    trainer_type: ppo

    hyperparameters:
      batch_size: 1048
      buffer_size: 10480
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear

    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0

    behavioral_cloning:
      demo_path: Assets/RECORDING/final.demo
      strength: 0.5
      steps: 1000000

    max_steps: 100000000
    time_horizon: 256
    summary_freq: 10000
    keep_checkpoints: 10
    checkpoint_interval: 500000
