# Imitation Learning (GAIL) Configuration for DroneAgent
# Use this for the first phase: learning from human demonstrations

behaviors:
  DroneAgent:
    trainer_type: ppo
    
    hyperparameters:
      batch_size: 512
      buffer_size: 5120
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    
    # GAIL settings for imitation learning
    reward_signals:
      gail:
        strength: 1.0
        gamma: 0.99
        encoding_size: 128
        demo_path: demonstrations/DroneAgent_demos.demo
        learning_rate: 3.0e-4
      
      # Reduce extrinsic reward during imitation phase
      extrinsic:
        strength: 0.01
        gamma: 0.99
    
    max_steps: 200000
    time_horizon: 64
    summary_freq: 5000
