behaviors:
  DroneAgent:
    trainer_type: ppo

    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear

    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0

    behavioral_cloning:
      demo_path: Assets/RECORDING/allmove_2.demo
      strength: 0.5
      steps: 500000

    max_steps: 10000000
    time_horizon: 128
    summary_freq: 5000
    keep_checkpoints: 10
