# PitchAgent - IMITATION LEARNING Configuration
# Learn pitch control from human demonstrations (simplest approach)
# Record demos with keyboard (Up/Down arrows), then train agent to copy

behaviors:
  PitchAgent:
    trainer_type: ppo
    
    hyperparameters:
      batch_size: 256           # Small batches
      buffer_size: 2560         # 10x batch size
      learning_rate: 3.0e-4     # Standard learning rate
      beta: 1.0e-2              # Higher entropy
      epsilon: 0.2              # PPO clip range
      lambd: 0.95               # GAE lambda
      num_epoch: 3              # Training passes
      learning_rate_schedule: constant
    
    network_settings:
      normalize: true           # Normalize observations
      hidden_units: 32          # Tiny network (only 3 observations!)
      num_layers: 1             # Single hidden layer
      vis_encode_type: simple
    
    # BEHAVIORAL CLONING - learn from demonstrations
    behavioral_cloning:
      demo_path: Assets/RECORDING/PitchDemo.demo  # Your recorded demos
      steps: 50000              # Use demos for first 50K steps
      strength: 1.0             # Strong imitation (1.0 = pure BC at start)
      batch_size: 128           # Demo batch size
      num_epoch: 3              # Epochs per demo update
      samples_per_update: 0     # Use all available demos
    
    reward_signals:
      extrinsic:
        gamma: 0.99             # Discount factor
        strength: 1.0           # Extrinsic reward weight
    
    max_steps: 200000           # 200K steps (imitation learns fast!)
    time_horizon: 64            # Episode steps
    summary_freq: 1000          # Frequent updates
    keep_checkpoints: 3         # Keep 3 checkpoints
    checkpoint_interval: 10000  # Save every 10K steps
